name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.2'
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v -t -d ./...
      env:
        GO111MODULE: "on"

    - name: Build
      run: go build -v ./...
      env:
        GO111MODULE: "on"

    - name: Test
      run: go test -v ./...
      env:
        GO111MODULE: "on"
