name: Release

on:
  push:
    tags:
      - 'v*'

jobs:


  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v3
      
    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build -o "release/aws-service-limits.$GOOS-$GOARCH"

    - uses: actions/upload-artifact@v3
      with:
        name: aws-service-limits
        path: release
        
  release:

    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@v2
      with:
        name: aws-service-limits
        path: release
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: release/*
